[".elixir-ls"]
  type = "archive"
  url = "https://github.com/elixir-lsp/elixir-ls/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "24h"
[".erlang_ls"]
  type = "archive"
  url = "https://github.com/erlang-ls/erlang_ls/archive/master.tar.gz"
  stripComponents = 1
  refreshPeriod = "24h"
[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.18.0.tar.gz"
  exact = true
  stripComponents = 1
{{- $fontDir := "" }}
{{- if eq .chezmoi.os "darwin" }}
{{-   $fontDir = "Library/Fonts" }}
{{- else if eq .chezmoi.os "linux" }}
{{-   $fontDir = ".local/share/fonts" }}
{{- end }}
["{{ $fontDir }}/MesloLGS NF Regular.ttf"]
  type = "file"
  url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Regular.ttf"
  refreshPeriod = "672h"
["{{ $fontDir }}/MesloLGS NF Bold.ttf"]
  type = "file"
  url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold.ttf"
  refreshPeriod = "672h"
["{{ $fontDir }}/MesloLGS NF Italic.ttf"]
  type = "file"
  url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Italic.ttf"
  refreshPeriod = "672h"
["{{ $fontDir }}/MesloLGS NF Bold Italic.ttf"]
  type = "file"
  url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf"
  refreshPeriod = "672h"
{{- $sublimePkgDir := "" }}
{{- if eq .chezmoi.os "darwin" }}
{{-   $sublimePkgDir = "Library/Application Support/Sublime Text/Installed Packages" }}
{{- else if eq .chezmoi.os "linux" }}
{{-   $sublimePkgDir = ".config/sublime-text-3/Installed Packages" }}
{{- end }}
["{{ $sublimePkgDir }}/Package Control.sublime-package"]
  type = "file"
  url = "https://packagecontrol.io/Package%20Control.sublime-package"
  refreshPeriod = "168h"
